### ISSUE TITLE
There is a minor UI bug on console.upstash.com

### ISSUE THREAD

**Issue by halilatilla** [upstash/react-ui#4]
I'm not sure that I'm in the right place but I want to notify you @ademilter  :)

https://user-images.githubusercontent.com/27916419/230718094-5e5c6352-448d-45c2-80d7-fdf2467bd20c.mp4

**Comment by halilatilla** [comment]
And this one on https://upstash.com 

![Screenshot 2023-05-19 at 10 56 06](https://github.com/upstash/react-ui/assets/27916419/c7790281-5638-4317-a2ff-e70276e19a7d)

**Comment by ogzhanolguncu** [comment]
Those issues are fixed now, closing the issue.
